export const GET_ALL_USER_ORDERS_REQUEST = 'GET_ALL_USER_ORDERS_REQUEST';
export const GET_ALL_USER_ORDERS_SUCCESS = 'GET_ALL_USER_ORDERS_SUCCESS';
export const GET_ALL_USER_ORDERS_FAIL = 'GET_ALL_USER_ORDERS_FAIL';