export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST';
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';
export const CART_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL';

export const CART_REMOVE_PRODUCT_REQUEST = 'CART_REMOVE_PRODUCT_REQUEST';
export const CART_REMOVE_PRODUCT_SUCCESS = 'CART_REMOVE_PRODUCT_SUCCESS';
export const CART_REMOVE_PRODUCT_FAIL = 'CART_REMOVE_PRODUCT_FAIL';

export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const EDIT_CART_QTY = 'EDIT_CART_QTY';
export const UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT';

export const GET_PRINTFUL_TOTAL_COSTS_REQUEST = 'GET_PRINTFUL_TOTAL_COSTS_REQUEST';
export const GET_PRINTFUL_TOTAL_COSTS_SUCCESS = 'GET_PRINTFUL_TOTAL_COSTS_SUCCESS';
export const GET_PRINTFUL_TOTAL_COSTS_FAIL = 'GET_PRINTFUL_TOTAL_COSTS_FAIL';

export const CART_EDIT_PRODUCT_REQUEST = 'CART_EDIT_PRODUCT_REQUEST';
export const CART_EDIT_PRODUCT_SUCCESS = 'CART_EDIT_PRODUCT_SUCCESS';
export const CART_EDIT_PRODUCT_FAIL = 'CART_EDIT_PRODUCT_FAIL';