export const CREATE_MEDIAMOD_MOCKUP_REQUEST = "CREATE_MEDIAMOD_MOCKUP_REQUEST";
export const CREATE_MEDIAMOD_MOCKUP_SUCCESS = "CREATE_MEDIAMOD_MOCKUP_SUCCESS";
export const CREATE_MEDIAMOD_MOCKUP_FAIL = "CREATE_MEDIAMOD_MOCKUP_FAIL";