export const SUBSCRIPTION_PRODUCT_REQUEST = 'SUBSCRIPTION_PRODUCT_REQUEST';
export const SUBSCRIPTION_PRODUCT_SUCCESS = 'SUBSCRIPTION_PRODUCT_SUCCESS';
export const SUBSCRIPTION_PRODUCT_FAIL = 'SUBSCRIPTION_PRODUCT_FAIL';

export const USER_STRIPE_PAYMENT_METHODS_REQUEST = 'USER_STRIPE_PAYMENT_METHODS_REQUEST';
export const USER_STRIPE_PAYMENT_METHODS_SUCCESS = 'USER_STRIPE_PAYMENT_METHODS_SUCCESS';
export const USER_STRIPE_PAYMENT_METHODS_FAIL = 'USER_STRIPE_PAYMENT_METHODS_FAIL';